default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: trackarep_development

test:
  <<: *default
  database: trackarep_test

staging:
  <<: *default
  database: trackarep_staging

production:
  <<: *default
  database: trackarep_production
